# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/confidence_based_routing',
                'doc_host': 'https://mshahoyi.github.io',
                'git_url': 'https://github.com/mshahoyi/confidence_based_routing',
                'lib_path': 'confidence_based_routing'},
  'syms': {'confidence_based_routing.core': {'confidence_based_routing.core.foo': ('core.html#foo', 'confidence_based_routing/core.py')}}}
